- Fixed an issue where picking an avatar from file manager in devices prior to Android Q would throw NoSuchMethodError; devices prior to Android Q now requires Read External Storage permission when picking up avatar  - It now show profiles that has upcoming birthdays in a separate section